[project]
name = "agents"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "scikit-learn",
    "langchain",
    "openai",
    "deepseek",
    "google-generativeai",
    "jupyterlab"
]

[tool.ruff]
line-length = 88

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
